services:
  - type: web
    name: handmade-store-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://handmade-store-delta.vercel.app
    healthCheckPath: /api/health
    autoDeploy: true 